/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2020-06-18 18:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hot_005fsale_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    <!--==================================================================== \n");
      out.write("            Start Special Offer Section\n");
      out.write("        =====================================================================-->\n");
      out.write("        <section class=\"special-offer text-center pt-110 rpt-70 pb-35\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"section-title mb-15\">\n");
      out.write("                    <h2>本周热卖</h2>\n");
      out.write("                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row justify-content-center\">\n");
      out.write("                    <div class=\"col-lg-10\">\n");
      out.write("\n");
      out.write("                        <div class=\"special-offer-inner special-offer-slider\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--single Product -->\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"special-offer-product bg-white m-25 p-25 b1 br-5\">\n");
      out.write("                                    <div class=\"off\">10%<span>off</span></div>\n");
      out.write("                                    <div class=\"product-img-wrap\">\n");
      out.write("                                        <img style = \"width:220px;height:215px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/drink/drink1.jpg\" alt=\"img\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"offer-product-price\">\n");
      out.write("                                            <span class=\"discounted-price\">￥18</span>\n");
      out.write("                                            <span class=\"actual-price has-discount\">￥20</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p>巧克力奶霜拿铁 </p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-action\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/#\" class=\"add-to-btn\">加入购物车</a>\n");
      out.write("                                       \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--single Product -->\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"special-offer-product bg-white m-25 p-25 b1 br-5\">\n");
      out.write("                                    <div class=\"off\">10%<span>off</span></div>\n");
      out.write("                                    <div class=\"product-img-wrap\">\n");
      out.write("                                        <img style = \"width:220px;height:215px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/drink/drink2.jpg\" alt=\"img\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"offer-product-price\">\n");
      out.write("                                            <span class=\"discounted-price\">￥9</span>\n");
      out.write("                                            <span class=\"actual-price has-discount\">￥10</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p>冻柠绿茶</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-action\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/#\" class=\"add-to-btn\">加入购物车</a>\n");
      out.write("                                        \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--single Product -->\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"special-offer-product bg-white m-25 p-25 b1 br-5\">\n");
      out.write("                                    <div class=\"off\">10%<span>off</span></div>\n");
      out.write("                                    <div class=\"product-img-wrap\">\n");
      out.write("                                        <img style = \"width:220px;height:215px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/drink/drink3.jpg\" alt=\"img\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"offer-product-price\">\n");
      out.write("                                            <span class=\"discounted-price\">￥22</span>\n");
      out.write("                                            <span class=\"actual-price has-discount\">￥25</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p>奥利奥星冰乐</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-action\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/#\" class=\"add-to-btn\">加入购物车</a>\n");
      out.write("                                        \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--single Product -->\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"special-offer-product bg-white m-25 p-25 b1 br-5\">\n");
      out.write("                                    <div class=\"off\">10%<span>off</span></div>\n");
      out.write("                                    <div class=\"product-img-wrap\">\n");
      out.write("                                        <img style = \"width:220px;height:215px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/drink/drink4.jpg\" alt=\"img\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"offer-product-price\">\n");
      out.write("                                            <span class=\"discounted-price\">￥18</span>\n");
      out.write("                                            <span class=\"actual-price has-discount\">￥20</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p>奥利奥奶盖茶</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-action\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/#\" class=\"add-to-btn\">加入购物车</a>\n");
      out.write("                                        \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--single Product -->\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"special-offer-product bg-white m-25 p-25 b1 br-5\">\n");
      out.write("                                    <div class=\"off\">10%<span>off</span></div>\n");
      out.write("                                    <div class=\"product-img-wrap\">\n");
      out.write("                                        <img style = \"width:220px;height:215px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/drink/drink5.png\" alt=\"img\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-content\">\n");
      out.write("                                        <div class=\"offer-product-price\">\n");
      out.write("                                            <span class=\"discounted-price\">￥18</span>\n");
      out.write("                                            <span class=\"actual-price has-discount\">￥20</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p>醇奶可可</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"product-action\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/#\" class=\"add-to-btn\">加入购物车</a>\n");
      out.write("                                        \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--==================================================================== \n");
      out.write("            End Special Offer Section\n");
      out.write("        =====================================================================-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
