/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2020-06-20 05:11:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quick_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--==================================== Start product-quick-view //product-modal  ================-->\r\n");
      out.write("\t<div class=\"modal product-modal fade\" id=\"quick-view\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body p-35 pt-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"product-quick-view\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t \t\t\t\t\t\t\t\t<div class=\"product-preview-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-content bg-white p-50 b1 br-5\">\r\n");
      out.write("\t                                                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"\" alt=\"Product Preview Image\" id=\"PicAddres\">\r\n");
      out.write("\t                                                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-details text-left bg-white ml-25 px-50 py-45 b1 br-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"mb-25 rmt-25\" id=\"DrinkName\"></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating mb-25\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"star mr-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"text\">(13 Review)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p id=\"DrinkDesc\"></p>\r\n");
      out.write("\t                                                                    \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <h6>Availability: <span>In Stock</span></h6> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"price\" id=\"DrinkPrice\"></h4>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product-spinner mt-20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"number-input b1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"minus\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input min=\"1\" name=\"quantity\" value=\"1\" type=\"number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"plus\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"theme-btn br-30 ml-20\">加入购物车</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class = \"choices mt-20\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"radio_submit\" method = \"get\">\r\n");
      out.write("\t\t                                                                    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class = \"choice-control choice-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6><b>请选择甜度</b> </h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type = \"radio\" class = \"choice-control-input\" name = \"sweet\" value = \"1\" checked> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"choice-control-label\" for=\"methodone\" data-toggle=\"collapse\" data-target=\"#collapseOne\" aria-controls=\"collapseOne\">全糖</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type = \"radio\" name = \"sweet\" value = \"2\"> <h7>七分糖</h7></label>\r\n");
      out.write("\t\t                                                                    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type = \"radio\" name = \"sweet\" value = \"3\"> <h7>半糖</h7></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type = \"radio\" name = \"sweet\" value = \"4\"> <h7>三分糖</h7></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--==================================== end product-quick-view //product-modal  ================-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
