/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2020-07-02 13:34:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admintable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/logo-mini.png\" type=\"image/x-icon\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction deleteAdmin (AdminID) {\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/deleteAdmin?AdminID=\" + AdminID;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <title>Admintable</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/cs-skin-elastic.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/lib/datatable/dataTables.bootstrap.min.css\">\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftbar.jsp", out, false);
      out.write("\n");
      out.write("<div id=\"right-panel\" class=\"right-panel\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- top bar -->\n");
      out.write("<div class=\"breadcrumbs\">\n");
      out.write("\t<div class=\"breadcrumbs-inner\">\n");
      out.write("    \t<div class=\"row m-0\">\n");
      out.write("        \t<div class=\"col-sm-4\">\n");
      out.write("                <div class=\"page-header float-left\">\n");
      out.write("                    <div class=\"page-title\">\n");
      out.write("                        <h1>后台管理系统</h1>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        <div class=\"col-sm-8\">\n");
      out.write("            <div class=\"page-header float-right\">\n");
      out.write("                 <div class=\"page-title\">\n");
      out.write("                      <ol class=\"breadcrumb text-right\">\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/showAdminIndex\">首页</a></li>\n");
      out.write("                          <li><a>用户列表</a></li>\n");
      out.write("                          <li class=\"active\">管理员表</li>\n");
      out.write("                       </ol>\n");
      out.write("                  </div>\n");
      out.write("             </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"content\">\n");
      out.write("            <div class=\"animated fadeIn\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-header\">\n");
      out.write("                                <strong class=\"card-title\">管理员表</strong>\n");
      out.write("                                <a class=\"btn btn-danger btn-sm\" href=\"#\" data-toggle=\"modal\" data-target=\"#addadmin\">\n");
      out.write("  \t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i> 添加</a>\n");
      out.write("  \t\t\t\t\t\t\t\t\n");
      out.write("  \t\t\t\t\t\t\n");
      out.write("  \t\t\t\t\t\t\t\t\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <table class=\"table table-striped table-bordered\" id=\"admintable\">\n");
      out.write("                                    <thead>\n");
      out.write("                                        <tr>\n");
      out.write("                                            <th>管理员id</th>\n");
      out.write("                                            <th>管理员姓名</th>\n");
      out.write("                                            <th>密码</th>\n");
      out.write("                                            <th>操作</th>\n");
      out.write("                                        </tr>\n");
      out.write("                                    </thead>\n");
      out.write("                                    <tbody>\n");
      out.write("                                         ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                        </tbody>\n");
      out.write("                                        \n");
      out.write("                                </table>\n");
      out.write("                                \n");
      out.write("                              \n");
      out.write("                              <!--修改模态框-->\n");
      out.write("                                <form id=\"myUpdateForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/changeAdmin\">\n");
      out.write("                                \t<input type=\"hidden\" id=\"update-adid\" name=\"update-adid\" value=\"\">\n");
      out.write("                                \t<div class=\"modal fade\" id=\"updateadmin\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">修改管理员信息</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\n");
      out.write("                                \t\t\t  <input type=\"hidden\" id=\"update-adid\" name=\"update-adid\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">修改管理员姓名</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"update-adname\" name=\"update-adname\" value=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">修改管理员密码</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"update-adpwd\" name=\"update-adpwd\" value=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t          \n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">确定</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("                                </form>\n");
      out.write("                                \n");
      out.write("                                \n");
      out.write("                                 <!-- 添加模态框 -->\n");
      out.write("                                <form id=\"myaddForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/addAdmin\">\n");
      out.write("                                \t<div class=\"modal fade\" id=\"addadmin\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">添加管理员</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">管理员姓名</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"add-adname\" name=\"add-adname\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">管理员密码</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"add-adpwd\" name=\"add-adpwd\">\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t          \n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">确定</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("                                </form>\n");
      out.write("                                \n");
      out.write("                                \n");
      out.write("                                \n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div><!-- .animated -->\n");
      out.write("        </div><!-- .content -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"clearfix\"></div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Scripts -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/datatables.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.buttons.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/jszip.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/vfs_fonts.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.html5.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.print.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.colVis.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/init/datatables-init.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() {\n");
      out.write("    $('#bootstrap-data-table-export').DataTable();\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(\"#updateadmin\").on('show.bs.modal', function (event) {\n");
      out.write("    var btnThis = $(event.relatedTarget); //触发事件的按钮\n");
      out.write("    var modal = $(this); //当前模态框\n");
      out.write("    var modalid = btnThis.data('id'); //解析出data-id的内容\n");
      out.write("    var modalname = btnThis.data('name'); //解析出data-name的内容\n");
      out.write("    var modalpwd = btnThis.data('pwd'); //解析出data-pwd的内容\n");
      out.write("    \n");
      out.write("    // 将从\"按钮\"解析出来的data值赋给\"模态框\"的input标签中对于的value里面\n");
      out.write("    $('#update-adid').attr('value', modalid);\n");
      out.write("    $('#update-adname').attr('value', modalname);\n");
      out.write("    $('#update-adpwd').attr('value', modalpwd);\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/admintable.jsp(86,41) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/admintable.jsp(86,41) '${adminList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${adminList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /admin/admintable.jsp(86,41) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("admin");
      // /admin/admintable.jsp(86,41) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                        <tr>\n");
            out.write("                                        \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("                                        \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("                                        \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("                                           \n");
            out.write("                                            <td>\n");
            out.write("                                            <div class=\"btn-group btn-group-justified\" role=\"group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"btn-group\" role=\"group\" style=\"margin-left:10px;margin-right:10px;\">\n");
            out.write("\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t     <button type=\"button\" class=\"btn btn-default btn-danger\" onclick=\"deleteAdmin('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">删除</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t <div class=\"btn-group\" role=\"group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <button type=\"button\" class=\"btn btn-default btn-primary\" data-toggle=\"modal\" data-target=\"#updateadmin\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-pwd=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    >修改</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
            out.write("                                        </tr>\n");
            out.write("                                       ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
