/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2020-07-02 07:38:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class drinktable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/logo-mini.png\" type=\"image/x-icon\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Drinktable</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/cs-skin-elastic.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/drinktable.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/lib/fileinput.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/lib/theme.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/lib/datatable/dataTables.bootstrap.min.css\">\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftbar.jsp", out, false);
      out.write("\r\n");
      out.write("<div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- top bar -->\r\n");
      out.write("<div class=\"breadcrumbs\">\r\n");
      out.write("\t<div class=\"breadcrumbs-inner\">\r\n");
      out.write("    \t<div class=\"row m-0\">\r\n");
      out.write("        \t<div class=\"col-sm-4\">\r\n");
      out.write("                <div class=\"page-header float-left\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <h1>后台管理系统</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"col-sm-8\">\r\n");
      out.write("            <div class=\"page-header float-right\">\r\n");
      out.write("                 <div class=\"page-title\">\r\n");
      out.write("                      <ol class=\"breadcrumb text-right\">\r\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/\">首页</a></li>\r\n");
      out.write("                          <li><a>商品订单</a></li>\r\n");
      out.write("                          <li class=\"active\">商品表</li>\r\n");
      out.write("                       </ol>\r\n");
      out.write("                  </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("            <div class=\"animated fadeIn\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header\">\r\n");
      out.write("                                <strong class=\"card-title mr-20\">商品表</strong>\r\n");
      out.write("                                <a class=\"btn btn-danger btn-sm\" href=\"#\" data-toggle=\"modal\" data-target=\"#adddrink\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i> 添加</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered\" id=\"drinktable\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                                \r\n");
      out.write("                                <!--添加模态框-->\r\n");
      out.write("                                \t<div class=\"modal fade\" id=\"adddrink\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("                                \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">添加饮品</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div id=\"kv-avatar-errors-2\" class=\"center-block\" style=\"width:800px;display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form class=\"form form-vertical\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/addDrink\" method=\"post\" id=\"addForm\" name=\"addForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input type=\"hidden\" id=\"add-PicAddres\" name=\"add-PicAddres\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"email\">饮品名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkName\" name=\"add-DrinkName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"pwd\">超级杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkPrice_Super\" name=\"add-DrinkPrice_Super\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"fname\">大杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkPrice_Big\" name=\"add-DrinkPrice_Big\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"lname\">中杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkPrice_Medium\" name=\"add-DrinkPrice_Medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"fname\">饮品类型</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkType\" name=\"add-DrinkType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"lname\">饮品描述</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"add-DrinkDesc\" name=\"add-DrinkDesc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        \t<div class=\"col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t<div class=\"kv-avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                \t<div class=\"file-loading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    \t<input id=\"addpic\" name=\"addpic\" type=\"file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <!-- <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"btn btn-primary\">确定</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--修改模态框-->\r\n");
      out.write("                                \t<div class=\"modal fade\" id=\"updatedrink\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">修改饮品</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div id=\"kv-avatar-errors-2\" class=\"center-block\" style=\"width:800px;display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form class=\"form form-vertical\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/changeDrink\" method=\"post\" id=\"updateForm\" name=\"updateForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <input type=\"hidden\" id=\"update-DrinkID\" name=\"update-DrinkID\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <input type=\"hidden\" id=\"update-PicAddres\" name=\"update-PicAddres\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"email\">饮品名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkName\" name=\"update-DrinkName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"pwd\">超级杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkPrice_Super\" name=\"update-DrinkPrice_Super\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"fname\">大杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkPrice_Big\" name=\"update-DrinkPrice_Big\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"lname\">中杯</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkPrice_Medium\" name=\"update-DrinkPrice_Medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"fname\">饮品类型</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkType\" name=\"update-DrinkType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <label for=\"lname\">饮品描述</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <input type=\"text\" class=\"form-control\" id=\"update-DrinkDesc\" name=\"update-DrinkDesc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <div class=\"col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <div class=\"kv-avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"file-loading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <input name=\"avatar-2\" type=\"file\" id=\"update-pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"btn btn-primary\" onclick=\"$('#updateForm').submit();\">确定</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- .animated -->\r\n");
      out.write("        </div><!-- .content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/datatables.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.buttons.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/jszip.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/vfs_fonts.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.html5.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.print.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.colVis.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/fileinput.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/zh.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/init/datatables-init.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var btnCust = '<button type=\"button\" style=\"background:#fff;border:none;\"> ' + '</button>'; \r\n");
      out.write("$(\"#addpic\").fileinput({\r\n");
      out.write("\tuploadUrl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/uploadPic\",\r\n");
      out.write("    overwriteInitial: true,\r\n");
      out.write("    maxFileSize: 1500,\r\n");
      out.write("    showUpload: true,\r\n");
      out.write("    showClose: false,\r\n");
      out.write("    showCaption: false,\r\n");
      out.write("    showBrowse: false,\r\n");
      out.write("    browseOnZoneClick: true,\r\n");
      out.write("    removeClass: \"btn btn-danger\",\r\n");
      out.write("    removeIcon: '<i class=\"fa fa-remove\"></i>',\r\n");
      out.write("    removeTitle: '取消',\r\n");
      out.write("    uploadClass:\"btn btn-primary\",\r\n");
      out.write("    uploadIcon:'<i class=\"fa fa-upload\" aria-hidden=\"true\"></i>',\r\n");
      out.write("    uploadTitle: '上传',\r\n");
      out.write("    elErrorContainer: '#kv-avatar-errors-2',\r\n");
      out.write("    msgErrorClass: 'alert alert-block alert-danger',\r\n");
      out.write("    defaultPreviewContent: '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/images/drinkdft.png\" alt=\"Your Avatar\"><h6 class=\"text-muted\">Click to select</h6>',\r\n");
      out.write("    layoutTemplates: {actionDelete:'', //去除上传预览的缩略图中的删除图标\r\n");
      out.write("        actionUpload:'',//去除上传预览缩略图中的上传图片；\r\n");
      out.write("        actionZoom:''   //去除上传预览缩略图中的查看详情预览的缩略图标。\r\n");
      out.write("        },\r\n");
      out.write("    allowedFileExtensions: [\"jpg\", \"png\", \"gif\"]\r\n");
      out.write("}).on(\"fileuploaded\", function(event, data, previewId, index) {\r\n");
      out.write("\tvar result = data.response;\r\n");
      out.write("\tif(result.state == \"success\") {\r\n");
      out.write("\t\t// 图片路径放入表单中\r\n");
      out.write("\t\t$('#add-PicAddres').attr('value',result.PicAddres);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 提交表单\r\n");
      out.write("\t$('#addForm').submit();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#updatedrink\").on('show.bs.modal', function (event) {\r\n");
      out.write("\tvar btnThis = $(event.relatedTarget); //触发事件的按钮\r\n");
      out.write("    var modal = $(this); //当前模态框\r\n");
      out.write("    var modalid = btnThis.data('id'); \r\n");
      out.write("    var modalname = btnThis.data('name');\r\n");
      out.write("    var modalsuper = btnThis.data('super'); \r\n");
      out.write("    var modalbig = btnThis.data('big');\r\n");
      out.write("    var modalmediu = btnThis.data('mediu');\r\n");
      out.write("    var modaltype = btnThis.data('type');\r\n");
      out.write("    var modalspec = btnThis.data('spec');\r\n");
      out.write("    var modalpic = btnThis.data('pic');\r\n");
      out.write("    \r\n");
      out.write("    // 将从\"按钮\"解析出来的data值赋给\"模态框\"的input标签中对于的value里面\r\n");
      out.write("    $('#update-PicAddres').attr('value', modalpic);\r\n");
      out.write("    $('#update-DrinkID').attr('value', modalid);\r\n");
      out.write("    $('#update-DrinkName').attr('value', modalname);\r\n");
      out.write("    $('#update-DrinkPrice_Super').attr('value', modalsuper);\r\n");
      out.write("    $('#update-DrinkPrice_Big').attr('value', modalbig);\r\n");
      out.write("    $('#update-DrinkPrice_Medium').attr('value', modalmediu);\r\n");
      out.write("    $('#update-DrinkType').attr('value', modaltype);\r\n");
      out.write("    $('#update-DrinkDesc').attr('value', modalspec);\r\n");
      out.write("\r\n");
      out.write("    $(\"#update-pic\").fileinput({\r\n");
      out.write("    \tuploadUrl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/uploadPic\",\r\n");
      out.write("        overwriteInitial: true,\r\n");
      out.write("        maxFileSize: 1500,\r\n");
      out.write("        showUpload: true,\r\n");
      out.write("        showClose: false,\r\n");
      out.write("        showCaption: false,\r\n");
      out.write("        showBrowse: false,\r\n");
      out.write("        browseOnZoneClick: true,\r\n");
      out.write("        removeClass: \"btn btn-danger\",\r\n");
      out.write("        removeIcon: '<i class=\"fa fa-remove\"></i>',\r\n");
      out.write("        removeTitle: '取消',\r\n");
      out.write("        uploadClass:\"btn btn-primary\",\r\n");
      out.write("        uploadIcon:'<i class=\"fa fa-upload\" aria-hidden=\"true\"></i>',\r\n");
      out.write("        uploadTitle: '上传',\r\n");
      out.write("        elErrorContainer: '#kv-avatar-errors-2',\r\n");
      out.write("        msgErrorClass: 'alert alert-block alert-danger',\r\n");
      out.write("        defaultPreviewContent: '<img id=\"defaultImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/images/drinkdft.png\" alt=\"Your Avatar\"><h6 class=\"text-muted\">Click to select</h6>',\r\n");
      out.write("        \r\n");
      out.write("        // overwriteInitial: false, //不覆盖已存在的图片\r\n");
      out.write("        /*//下面几个就是初始化预览图片的配置\r\n");
      out.write("        initialPreviewAsData: true,\r\n");
      out.write("        initialPreviewFileType: 'image',\r\n");
      out.write("        initialPreview: modalpic,\r\n");
      out.write("        initialPreviewConfig: [\r\n");
      out.write("            {caption: modalpic, size: 576237, width: \"120px\", url: modalpic, key: 1},\r\n");
      out.write("        ],*/\r\n");
      out.write("        \r\n");
      out.write("        layoutTemplates: {actionDelete:'', //去除上传预览的缩略图中的删除图标\r\n");
      out.write("            actionUpload:'',//去除上传预览缩略图中的上传图片；\r\n");
      out.write("            actionZoom:''   //去除上传预览缩略图中的查看详情预览的缩略图标。\r\n");
      out.write("            },\r\n");
      out.write("        allowedFileExtensions: [\"jpg\", \"png\", \"gif\"]\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('#defaultImg').attr('src', \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/\" + modalpic);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#update-pic\").on(\"fileuploaded\", function(event, data, previewId, index) {\r\n");
      out.write("\tvar result = data.response;\r\n");
      out.write("\tif(result.state == \"success\") {\r\n");
      out.write("\t\t// 图片路径放入表单中\r\n");
      out.write("\t\t$('#update-PicAddres').attr('value',result.PicAddres);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 提交表单\r\n");
      out.write("\t$('#updateForm').submit();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function deleteDrink (DrinkID) {\r\n");
      out.write("\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/deleteDrink?DrinkID=\" + DrinkID;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/drinktable.jsp(68,36) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/drinktable.jsp(68,36) '${drinkList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${drinkList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /admin/drinktable.jsp(68,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("drink");
      // /admin/drinktable.jsp(68,36) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                        \t<td>\r\n");
            out.write("                                        \t\t<img style=\"width:60px;height:60px;border-radius:5px;\" alt=\"img\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("/client/img/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.picAddres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" class=\"pic\">\r\n");
            out.write("                                        \t</td>\r\n");
            out.write("                                        \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td class=\"name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Super}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Big}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Medium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td class=\"spec\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td> \r\n");
            out.write("                                        \t<td class=\"addr\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.picAddres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>\r\n");
            out.write("                                            <div class=\"btn-group btn-group-justified\" role=\"group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"btn-group\" role=\"group\" style=\"margin-left:10px;margin-right:10px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    <button type=\"button\" class=\"btn btn-default btn-danger\" onclick=\"deleteDrink('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\">删除</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"btn-group\" role=\"group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    <button type=\"button\" class=\"btn btn-default btn-primary\" data-toggle=\"modal\" data-target=\"#updatedrink\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-pic=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.picAddres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-super=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Super}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-big=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Big}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-mediu=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkPrice_Medium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-type=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-spec=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drink.drinkDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    >修改</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("                                        </tr>\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
