/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2020-07-02 11:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usertable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/client/img/logo-mini.png\" type=\"image/x-icon\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/userForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <title>Usertable</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css\">\r\n");
      out.write("    <!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css\">  -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/cs-skin-elastic.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/css/lib/datatable/dataTables.bootstrap.min.css\">\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftbar.jsp", out, false);
      out.write("\r\n");
      out.write("<div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- top bar -->\r\n");
      out.write("<div class=\"breadcrumbs\">\r\n");
      out.write("\t<div class=\"breadcrumbs-inner\">\r\n");
      out.write("    \t<div class=\"row m-0\">\r\n");
      out.write("        \t<div class=\"col-sm-4\">\r\n");
      out.write("                <div class=\"page-header float-left\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <h1>后台管理系统</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"col-sm-8\">\r\n");
      out.write("            <div class=\"page-header float-right\">\r\n");
      out.write("                 <div class=\"page-title\">\r\n");
      out.write("                      <ol class=\"breadcrumb text-right\">\r\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/showAdminIndex\">首页</a></li>\r\n");
      out.write("                          <li><a>用户列表</a></li>\r\n");
      out.write("                          <li class=\"active\">用户表</li>\r\n");
      out.write("                       </ol>\r\n");
      out.write("                  </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("            <div class=\"animated fadeIn\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header\">\r\n");
      out.write("                                <strong class=\"card-title mr-20\">用户表</strong>\r\n");
      out.write("                                <a class=\"btn btn-danger btn-sm\" href=\"#\" data-toggle=\"modal\" data-target=\"#adduser\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i> 添加</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered\" id=\"usertable\">\r\n");
      out.write("                                <!--<thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>用户id</th>\r\n");
      out.write("                                            <th>用户名</th>\r\n");
      out.write("                                            <th>密码</th>\r\n");
      out.write("                                            <th>联系方式</th>\r\n");
      out.write("                                            <th>操作</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>  -->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                                \r\n");
      out.write("                                <!--修改模态框-->\r\n");
      out.write("                                <form id=\"myUpdateForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/changeUser\" onsubmit=\"return checkUpdateFrom();\">\r\n");
      out.write("                                \t<input type=\"hidden\" id=\"update-id\" name=\"update-id\" value=\"\">\r\n");
      out.write("                                \t<input type=\"hidden\" id=\"oldName\" name=\"oldName\" value=\"\">\r\n");
      out.write("                                \t<div class=\"modal fade\" id=\"updateuser\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">修改用户信息</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("                                \t\t\t  <input type=\"hidden\" id=\"update-id\" name=\"update-id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">修改用户名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"update-name\" name=\"update-name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkUpdateName()\" onblur=\"checkUpdateSameName()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"update-nameMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">修改密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"update-pwd\" name=\"update-pwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkUpdatePwd()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"update-pwdMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">修改联系方式</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"update-pho\" name=\"update-pho\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkUpdatePhone()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"update-phoMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">确定</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                \r\n");
      out.write("                                <!-- 添加模态框 -->\r\n");
      out.write("                                <form id=\"myaddForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/addUser\" onsubmit=\"return checkAddFrom();\">\r\n");
      out.write("                                \t<div class=\"modal fade\" id=\"adduser\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <h4 class=\"modal-title\" id=\"exampleModalLabel\">添加用户</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">用户名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"add-name\" name=\"add-name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkAddName()\" onblur=\"checkAddSameName()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"add-nameMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"add-pwd\" name=\"add-pwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkAddPwd()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"add-pwdMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <label for=\"recipient-name\" class=\"control-label\">联系方式</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <input type=\"text\" class=\"form-control\" id=\"add-pho\" name=\"add-pho\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" onkeyup=\"checkAddPhone()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <span id=\"add-phoMsg\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">确定</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- .animated -->\r\n");
      out.write("        </div><!-- .content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/datatables.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/dataTables.buttons.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/jszip.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/vfs_fonts.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.html5.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.print.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/lib/data-table/buttons.colVis.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/assets/js/init/datatables-init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("          $('#bootstrap-data-table-export').DataTable();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function deleteUser (UserID) {\r\n");
      out.write("        \twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/deleteUser?UserID=\" + UserID;\r\n");
      out.write("        }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/usertable.jsp(78,36) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/usertable.jsp(78,36) '${userList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /admin/usertable.jsp(78,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /admin/usertable.jsp(78,36) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                        \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td> \r\n");
            out.write("                                        \t\r\n");
            out.write("                                            <td>\r\n");
            out.write("                                            <div class=\"btn-group btn-group-justified\" role=\"group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"btn-group\" role=\"group\" style=\"margin-left:10px;margin-right:10px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    <button type=\"button\" class=\"btn btn-default btn-danger\" onclick=\"deleteUser('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">删除</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"btn-group\" role=\"group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    <button type=\"button\" class=\"btn btn-default btn-primary\" data-toggle=\"modal\" data-target=\"#updateuser\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-pwd=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    data-pho=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t    >修改</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("                                        </tr>\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
